version: '3.8'

services:
  photowake-frontend:
    image: ghcr.io/slince-zero/photowake-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  photowake-backend:
    image: ghcr.io/slince-zero/photowake-backend:latest
    ports:
      - "3080:3080"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      photowake-frontend:
        condition: service_started
      photowake-backend:
        condition: service_started 