version: '3.8'

services:
  photowake-frontend:
    image: ghcr.io/slince-zero/photowake-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  photowake-backend:
    image: ghcr.io/slince-zero/photowake-backend:latest
    ports:
      - "3080:3080"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - photowake-frontend
      - photowake-backend
    command: |
      /bin/sh -c "echo 'server {
        listen 80;
        server_name _;

        # Frontend
        location / {
          proxy_pass http://photowake-frontend:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade \$$http_upgrade;
          proxy_set_header Connection \"upgrade\";
          proxy_set_header Host \$$host;
          proxy_cache_bypass \$$http_upgrade;
        }

        # Backend API
        location /api {
          rewrite ^/api/(.*) /\$$1 break;
          proxy_pass http://photowake-backend:3080;
          proxy_http_version 1.1;
          proxy_set_header Upgrade \$$http_upgrade;
          proxy_set_header Connection \"upgrade\";
          proxy_set_header Host \$$host;
          proxy_cache_bypass \$$http_upgrade;
        }

        # Health check endpoint
        location /health {
          proxy_pass http://photowake-backend:3080/health;
          proxy_http_version 1.1;
          proxy_set_header Host \$$host;
          proxy_cache_bypass \$$http_upgrade;
        }
      }' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
