version: '3.8'

services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    restart: always

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}-backend:latest
    ports:
      - "3080:3080"
    env_file:
      - ./server/.env
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      front:
        condition: service_started
      backend:
        condition: service_started
