FROM node:20-alpine

LABEL description="Backend server for avatar generator"

WORKDIR /app

COPY package.json ./

RUN npm install -g pnpm && pnpm install

COPY . .

RUN pnpm run build

EXPOSE 3080

ENV NODE_ENV=production
ENV PORT=3080

CMD ["pnpm", "run", "start"]
