FROM node:20-alpine

LABEL description="Backend server for avatar generator"

WORKDIR /server

COPY package.json package-lock.json ./

RUN npm install -g pnpm && pnpm install

COPY . .

RUN pnpm run build

EXPOSE 3080

ENV NODE_ENV=production

CMD ["pnpm", "run", "dev"]
