FROM node:20-alpine

# 添加构建参数
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

WORKDIR /web

COPY package.json ./

RUN npm install -g pnpm && pnpm install

COPY . .

ENV NODE_ENV=production
RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start"]
